# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v0.2.0
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
advanced: true
capitalize_platforms: true
classname: Noophaestus
generate_vscode: true
github_repo: noophaestus
github_user: SuperKnux
gradle_deps_type: gradle/libs.versions.toml
gradle_hex_version_key: hexcasting
gradle_mod_version_key: modVersion
main_branch: main
minecraft_version: 1.20.1
minecraft_version_in_mod_version: false
mod_description: An addon for Hex Casting that involves manipulation, creation and
    modification of enchantments.
mod_display_name: Noophaestus
modid: noophaestus
multiloader: true
package_name: hexdoc-noophaestus
package_slug: hexdoc_noophaestus
pages_url: https://superknux.github.io/noophaestus
pattern_registry_path: main/kotlin/at/ski/noophaestus/registry/NoophaestusActions.kt
source_url: https://github.com/SuperKnux/noophaestus
